### ISSUE TITLE
CR-01 - Provide an at-a-glance display of the cash amount available

### ISSUE THREAD

**Issue by thirilwin** [Rhican/SCM-Workshop2-PT08#1]
To aid the Maintainer, The system is required to provide an at-a-glance display of the cash amount available, by denomination, for collection by the Maintainer.  This will enable the Maintainer to readily tally the total cash collected and the total number of coins by denomination displayed in “Show Total Cash Held” and “Press to Collect Cash” when pressed, thus leaving no room for dispute over system errors.

**Comment by Rhican** [comment]
2821aa9da9714a1ffa85ed13c27cf089226da786 Design Model Report has been updated for this CR change,

**Comment by Rhican** [comment]
@muguatnus  Please implement it

**Comment by muguatnus** [comment]
@Rhican I have implemented the CR-01. Please review

**Comment by Rhican** [comment]
@muguatnus code reviewed -  good.

**Comment by Rhican** [comment]
@misite Please test this.

**Comment by misite** [comment]
Test Validation Passed. @Rhican Please proceed.

**Comment by Rhican** [comment]
@misite Thank you.

@thirilwin This feature is complete.

**Comment by thirilwin** [comment]
Thank you team.
