### ISSUE TITLE
CR-02 Reset the values to null for “Show Total Cash Held” and “Press to Collect Cash” 

### ISSUE THREAD

**Issue by thirilwin** [Rhican/SCM-Workshop2-PT08#2]
Reset the values to null for “Show Total Cash Held” and “Press to Collect Cash” when the Maintainer successfully pushed “Press Here When Finished”.

**Comment by Rhican** [comment]
This is a valid bug.

**Comment by Rhican** [comment]
bug fix branch "BugFix R1.0.8" has been created.

@phyumezaw Please fix this as we discussed over this issue.

**Comment by phyumezaw** [comment]
@Rhican . This issue has been fixed. Please review.

**Comment by Rhican** [comment]
@phyumezaw Code reviewed good. Thank you.

**Comment by misite** [comment]
@Rhican Testing complete and it is passed.

**Comment by Rhican** [comment]
@thirilwin This issue has been fixed and completed test. please close it.

**Comment by thirilwin** [comment]
Thank you team
